version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
  kibana:
    build: ./kibana
    ports:
      - 5601:5601
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
